enabled: true
copyright: 'Copyright   © 2017 Travel Guide. All rights reserved.'
bottom_links:
  -
    url: /privacy
    label: 'Privacy Policy'
  -
    url: /terms
    label: 'Terms of Use'
footer_links_1:
  headline: Destinations
  items:
    -
      url: '#'
      label: 'Nam elit magna, hendrerit'
    -
      url: '#'
      label: 'Quisque nullatibulum libero'
    -
      url: '#'
      label: 'Scelerisque eget, malesuada at'
    -
      url: '#'
      label: 'Vivamus eget niiam cursus leo'
    -
      url: '#'
      label: 'Nulla facilisinean nec eros'
footer_links_2:
  headline: Links
  items:
    -
      url: '#'
      label: 'Nam elit magna, hendrerit'
    -
      url: '#'
      label: 'Quisque nullatibulum libero'
    -
      url: '#'
      label: 'Scelerisque eget, malesuada at'
    -
      url: '#'
      label: 'Vivamus eget niiam cursus leo'
    -
      url: '#'
      label: 'Nulla facilisinean nec eros'
contact:
  headline: Contacts
  content: 'Call for more information:<br><span>1 800 123 4567</span><br>8901 Marmora Road,<br>Glasgow, D04 89GR.<br>Telephone: +1 800 123 1234<br>E-mail: <a href="mailto:mail@bteamny.com">mail@bteamny.com</a>'
logo:
  user/themes/travel/images/logo.png:
    name: logo.png
    type: image/png
    size: 5932
    path: user/themes/travel/images/logo.png
favicon:
  user/themes/travel/images/favicon.ico:
    name: favicon.ico
    type: image/vnd.microsoft.icon
    size: 1150
    path: user/themes/travel/images/favicon.ico
social_networks:
  headline: 'Follow Us'
  items:
    -
      url: '#'
      image:
        user/themes/travel/images/social_ic1.png: { name: social_ic1.png, type: image/png, size: 2168, path: user/themes/travel/images/social_ic1.png }
    -
      url: 'https://www.facebook.com'
      image:
        user/themes/travel/images/social_ic2.png: { name: social_ic2.png, type: image/png, size: 1912, path: user/themes/travel/images/social_ic2.png }
    -
      url: '#'
      image:
        user/themes/travel/images/social_ic3.png: { name: social_ic3.png, type: image/png, size: 2058, path: user/themes/travel/images/social_ic3.png }
    -
      url: '#'
      image:
        user/themes/travel/images/social_ic4.png: { name: social_ic4.png, type: image/png, size: 2375, path: user/themes/travel/images/social_ic4.png }
    -
      url: '#'
      image:
        user/themes/travel/images/social_ic5.png: { name: social_ic5.png, type: image/png, size: 2194, path: user/themes/travel/images/social_ic5.png }
    -
      url: '#'
      image:
        user/themes/travel/images/social_ic6.png: { name: social_ic6.png, type: image/png, size: 2075, path: user/themes/travel/images/social_ic6.png }
blog-page: /blog
